### ISSUE TITLE
Make possible to skip gutter around columns

### ISSUE THREAD

**Issue by gish** [nordnet/grid#23]
Sometimes it's desired to create a grid without the outer gutters. This means there's no gutter by the left side of the first column and no gutter by the right side of the last column. Right now we've had to create our own lightweight grid to conform to the design requirements.

**Comment by gish** [comment]
One option to achieve this is to add `noLeftPadding` and `noRightPadding` props to the `Col` component.

**Comment by gish** [comment]
ping @iamstarkov @bstream

**Comment by mlenser** [comment]
This could potentially be desired on a row by row level as well, but that should be rare.

What are the design requirements that don't want a gutter? How does that behave on mobile?

**Comment by gish** [comment]
The desktop design has a nested grid with two main columns, where the second/last one contains two columns. These two should use the full width of the parent column, while there's still spacing between them.

```
+---------------------------------+
| +---------+ +--------+--------+ |
| |  1      | | 2      | 3      | |
| +---------+ +--------+--------+ |
+---------------------------------+
```
Column 2 and 3 are descendants of the same parent column.

**Comment by mlenser** [comment]
Fully agreed on this, ran into this issue today. I'll see if I can make a PR quickly
